### ISSUE TITLE
Build fails through swiftpm

### ISSUE THREAD

**Issue by keith** [Zewo/Scribe#1]
Currently including only LoggerMiddleware via swiftpm fails to build for me with this error:

```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: /Users/ksmiley/dev/swiftserver/.build/debug/Middleware.a(Middleware.swift.o) has no symbols
Compiling Swift Module 'LoggerMiddleware' (1 sources)
<unknown>:0: error: missing required module 'CURIParser'
<unknown>:0: error: build had 1 command failures
error: exit(1): ["/Library/Developer/Toolchains/swift-2.2-SNAPSHOT-2016-01-11-a.xctoolchain/usr/bin/swift-build-tool", "-f", "/Users/ksmiley/dev/swiftserver/.build/debug/LoggerMiddleware.o/llbuild.yaml"]
```

It looks like this might be a bug in swiftpm. But I was able to fix this by adding the dependency of `CURIParser` directly to `LoggerMiddleware` (instead of indirectly via `Middleware`).

**Comment by keith** [comment]
As a somewhat related sidenote should we be using this repo or the [logger in the main Middleware repo](https://github.com/Zewo/Middleware/blob/master/Sources/LoggerMiddleware.swift)?

**Comment by paulofaria** [comment]
Yeah this repo is deprecated. I'll remove it in the future. But yes I think this is a bug in swiftpm. It doesn't fetch the C lib dependencies automatically 😒.

**Comment by keith** [comment]
Might be worth adding something to the description/readme. I can submit a PR if you'd like
